name: Build Flutter android app

on:
  - pull_request
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client/
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '12.x'
          cache: 'gradle'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          cache: true
      - run: flutter pub get
      - run: dart format --set-exit-if-changed lib/
      - run: flutter analyze
      - name: Run tests
        run: flutter test
      - run: flutter build apk
      - uses: pipe-cd/actions-gh-release@v2.3.4
        with:
          release_file: build/app/outputs/apk/release/app-release.apk
          token: ${{ secrets.GITHUB_TOKEN }}
