name: Build Flutter android app

on:
  - pull_request
  - workflow_dispatch

jobs:
  build:
    #permissions: write-all
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client/
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '12.x'
          cache: 'gradle'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          cache: true
      - run: flutter pub get
      - run: dart format --set-exit-if-changed lib/
      - run: flutter analyze
      - name: Run tests
        run: flutter test
      - run: flutter build apk
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: client/build/app/outputs/flutter-apk/app-release.apk
          prerelease: true
          tag_name: new_release
