name: Try building Flutter project

on:
  workflow_call:
    inputs:
      path_to_project:
        required: true
        type: string

jobs:
  try_building_android:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.path_to_project }}
    
    steps:
      - name: building_android_debug_apk
        run: flutter build apk --debug
