name: Flutter setup

on:
  workflow_call:
    inputs:
      path_to_project:
        required: true
        type: string

jobs:
  flutter_setup:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.path_to_project }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Java setup
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '12.x'
          cache: 'gradle'
      - name: Flutter setup
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          cache: true
      - name: Flutter get dependencies
        run: flutter pub get
