name: Test Flutter App

on:
  workflow_call:
    inputs:
      path_to_project:
        required: true
        type: string

jobs:
  test_application:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.path_to_project }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      # - name: Java setup
      #   uses: actions/setup-java@v3
      #   with:
      #     distribution: 'zulu'
      #     java-version: '12.x'
      #     cache: 'gradle'
      - name: Flutter setup
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          cache: true
      - name: Flutter get dependencies
        run: flutter pub get
      - name: Flutter setup
        uses: ./.github/flutter_setup.yml
      - name: Check code formatting
        run: dart format --set-exit-if-changed lib/
      - name:  Analyze project
        run: flutter analyze
      - name: Run tests
        run: flutter test
