name: Pull request workflow

on:
  - pull_request
  - workflow_dispatch

jobs:
  test_flutter:
    uses: ./.github/workflows/flutter_tests.yml
    with:
      path_to_project: client/


  try_build_proj:
    uses: ./.github/workflows/flutter_try_build.yml
    with:
      path_to_project: client/

