name: Pull request workflow

on:
  - pull_request
  - workflow_dispatch

env:
  FLUTTER_PROJ_DIR: client/

jobs:
  test_flutter:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Flutter
        uses: ./.github/flutter_setup.yml@main
        with:
          path_to_project: $FLUTTER_PROJ_DIR
      - name: Run flutter tests
        uses: ./.github/flutter_tests.yml@main
        with:
          path_to_project: $FLUTTER_PROJ_DIR


  try_build_proj:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Flutter
        uses: ./.github/flutter_setup.yml@main
        with:
          path_to_project: $FLUTTER_PROJ_DIR
      - name: Try building Flutter project
        uses: ./.github/flutter_try_build.yml@main
        with:
          path_to_project: $FLUTTER_PROJ_DIR
